

// src: https://brainder.org/2012/09/23/the-nifti-file-format/
/*
enum WBNiftiDArrayIntent {
    None ,
    Correlation = 2,
    tTest,
    FTest,
    zScore,
    X2Statistic,
    betaDistribution,
    BinomialDistribution,
    GammaDistribution,
    PoissonDistribution,
    NormalDistribution,
    NonCentralFStatistic,
    NonCentralX2Statistic,
    LogisticDistribution,
    LaplaceDistribution,
    UniformDistribution,
    NoncentralTStatistic,
    WeibullDistribution,
    XDistribution,
    InverseGaussian,
    ExtremeValueTypeI,
    pValue,
    ln,
    log,
    Estimate=1001,
    Label,
    NeuroName,
    GenericMatrix,
    SymmetricMatrix,
    DisplacementVector,
    Vector,
    PointSet,
    Triangle,
    Quaternion,
    Dimless,
    TimeSeries=2002,
    NodeIndex,
    RGB,
    RGBA,
    Shape
}*/
// src: https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/group__NIFTI1__INTENT__CODES.html/document_view
enum WBNiftiIntent {
    NIFTI_INTENT_NONE,
    NIFTI_INTENT_CORREL = 2,
    NIFTI_INTENT_TTEST,
    NIFTI_INTENT_FTEST,
    NIFTI_INTENT_ZSCORE,
    NIFTI_INTENT_CHISQ,
    NIFTI_INTENT_BETA,
    NIFTI_INTENT_BINOM,
    NIFTI_INTENT_GAMMA,
    NIFTI_INTENT_POISSON,
    NIFTI_INTENT_NORMAL,
    NIFTI_INTENT_FTEST_NONC,
    NIFTI_INTENT_CHISQ_NONC,
    NIFTI_INTENT_LOGISTIC,
    NIFTI_INTENT_LAPLACE,
    NIFTI_INTENT_UNIFORM,
    NIFTI_INTENT_TTEST_NONC,
    NIFTI_INTENT_WEIBULL,
    NIFTI_INTENT_CHI,
    NIFTI_INTENT_INVGAUSS,
    NIFTI_INTENT_EXTVAL,
    NIFTI_INTENT_PVAL,
    NIFTI_INTENT_LOGPVAL,
    NIFTI_INTENT_LOG10PVAL,
    NIFTI_FIRST_STATCODE,
    NIFTI_LAST_STATCODE,
    NIFTI_INTENT_ESTIMATE = 1001,
    NIFTI_INTENT_LABEL,
    NIFTI_INTENT_NEURONAME,
    NIFTI_INTENT_GENMATRIX,
    NIFTI_INTENT_SYMMATRIX,
    NIFTI_INTENT_DISPVECT,
    NIFTI_INTENT_VECTOR,
    NIFTI_INTENT_POINTSET,
    NIFTI_INTENT_TRIANGLE,
    NIFTI_INTENT_QUATERNION,
    NIFTI_INTENT_DIMLESS
}

/*
// src: https://brainder.org/2012/09/23/the-nifti-file-format/
enum WBNiftiDataType{
    unknown=0,
    bool=1,
    unsignedChar=2,
    signedShort=4,
    signedInt=8,
    NIFTI_TYPE_FLOAT32=16,
    complex=32,
    double=64,
    RGB=128,
    all=255,
    signedChar=256,
    unsignedShort=512,
    unsignedInt=768,
    lonLong=1024,
    unsignedLongLong=1280,
    longDouble=1536,
    doublePair=1792,
    longDoublePair=2048,
    RGBA=2304
}
*/

enum WBNiftiDataType {
    NIFTI_TYPE_UNKNOWN,
    NIFTI_TYPE_UINT8=2,
    NIFTI_TYPE_INT16=4,
    NIFTI_TYPE_INT32=8,
    NIFTI_TYPE_FLOAT32=16,
    NIFTI_TYPE_COMPLEX64=32,
    NIFTI_TYPE_FLOAT64=64,
    NIFTI_TYPE_RGB24=128,
    NIFTI_TYPE_INT8=256,
    NIFTI_TYPE_UINT16=512,
    NIFTI_TYPE_UINT32=768,
    NIFTI_TYPE_INT64=1024,
    NIFTI_TYPE_UINT64=1280,
    NIFTI_TYPE_FLOAT128=1536,
    NIFTI_TYPE_COMPLEX128=1792,
    NIFTI_TYPE_COMPLEX256=2048
}
export {WBNiftiIntent, WBNiftiDataType};
